### ISSUE TITLE
Stream and  OpenCV

### ISSUE THREAD

**Issue by Cap-n-Proud** [slowrunner/Carl#7]
Greetings and congrats for your robot!

I was trying to add OpenCV to the streaming example (https://github.com/slowrunner/Carl/tree/master/Examples/pycam/pistreaming). 

The idea for a start is to draw a simple square on top of the video. I understand this can be done either in the  class `StreamingOutput(object) `or in the class `StreamingHandler(server.BaseHTTPRequestHandler)`, and the code for the rectangle will look like that: ` cv2.rectangle(cv2.imread(self.buffer), start_point, end_point, color, thickness) `

However when I try to do so  the stream breaks and I only see the blank screen the the waiting for stream message.

Any idea on how to make it work?

**Comment by slowrunner** [comment]
@Cap-n-Proud, I don't have a clue how to merge these two ideas, picamera handler stream and an OpenCV stream.  The reason for the picamera stream handlers not having OpenCv is to minimize latency.  When I run OpenCV programs on my RPi 3B, the frame rates are 1 to 10 fps, so it is understandable that folks want to avoid OpenCV in the stream.   

I don't really understand all this vision stuff, but I did find one example of drawing boxes on video that does not use OpenCV, perhaps it has some useful ideas:  https://github.com/slowrunner/Carl/tree/master/Examples/pycam/MotionDetect
